"""
Lookalike / TAM models — Cluster qualified leads by business model,
then find lookalike companies via Apollo, Yandex, Google.
"""
import enum
from sqlalchemy import (
    Column, Integer, String, DateTime, Text, ForeignKey,
    Boolean, Float, Enum as SQLEnum, Index, UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db import Base


class LookalikeRunStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PAUSED = "PAUSED"
    FAILED = "FAILED"


class LookalikePhase(str, enum.Enum):
    APOLLO = "APOLLO"
    YANDEX = "YANDEX"
    GOOGLE = "GOOGLE"


class LookalikeCluster(Base):
    """
    A cluster of qualified leads sharing a precise business model.
    Search strategy is generated per-cluster for targeted lookalike search.
    """
    __tablename__ = "lookalike_clusters"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)

    name = Column(String(255), nullable=False)
    business_model = Column(Text, nullable=False)
    offer_fit = Column(JSONB, default=list)  # e.g. ["pay_gate", "payout"]

    # Search strategy — generated by Gemini
    search_strategy = Column(JSONB, nullable=True)
    # {
    #   "apollo_keywords": [...], "apollo_locations": [...],
    #   "yandex_queries": [...], "google_queries": [...],
    #   "doc_keywords": [...], "anti_keywords": [...],
    #   "analysis_prompt_override": "..."
    # }

    # KPI counters
    qualified_lead_count = Column(Integer, default=0)
    apollo_companies_found = Column(Integer, default=0)
    yandex_targets_found = Column(Integer, default=0)
    google_targets_found = Column(Integer, default=0)
    total_lookalikes = Column(Integer, default=0)

    is_active = Column(Boolean, default=True, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    members = relationship("ClusterMember", back_populates="cluster", cascade="all, delete-orphan")
    runs = relationship("LookalikeRun", back_populates="cluster", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_lookalike_clusters_project", "project_id", "is_active"),
    )


class ClusterMember(Base):
    """
    A qualified lead assigned to a cluster, with per-contact analysis.
    """
    __tablename__ = "cluster_members"

    id = Column(Integer, primary_key=True, index=True)
    cluster_id = Column(Integer, ForeignKey("lookalike_clusters.id", ondelete="CASCADE"), nullable=False, index=True)
    contact_id = Column(Integer, ForeignKey("contacts.id", ondelete="CASCADE"), nullable=False, index=True)

    business_model_description = Column(Text, nullable=True)
    offer_fit = Column(JSONB, default=list)
    website_scraped = Column(Boolean, default=False)
    analysis_data = Column(JSONB, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    cluster = relationship("LookalikeCluster", back_populates="members")
    contact = relationship("Contact")

    __table_args__ = (
        UniqueConstraint("cluster_id", "contact_id", name="uq_cluster_member"),
    )


class LookalikeRun(Base):
    """
    A search execution run for a cluster — phases: Apollo → Yandex → Google.
    """
    __tablename__ = "lookalike_runs"

    id = Column(Integer, primary_key=True, index=True)
    cluster_id = Column(Integer, ForeignKey("lookalike_clusters.id", ondelete="CASCADE"), nullable=False, index=True)
    project_id = Column(Integer, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True)
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False)

    status = Column(
        SQLEnum(LookalikeRunStatus, name="lookalike_run_status", create_type=True),
        default=LookalikeRunStatus.PENDING, nullable=False,
    )
    current_phase = Column(
        SQLEnum(LookalikePhase, name="lookalike_phase", create_type=True),
        nullable=True,
    )

    # FK to search jobs created by each phase
    apollo_job_id = Column(Integer, ForeignKey("search_jobs.id", ondelete="SET NULL"), nullable=True)
    yandex_job_id = Column(Integer, ForeignKey("search_jobs.id", ondelete="SET NULL"), nullable=True)
    google_job_id = Column(Integer, ForeignKey("search_jobs.id", ondelete="SET NULL"), nullable=True)

    # Budget caps
    budget_apollo_credits = Column(Integer, default=500)
    budget_yandex_queries = Column(Integer, default=200)
    budget_google_queries = Column(Integer, default=50)

    # Stats & results
    stats = Column(JSONB, default=dict)
    total_lookalikes_found = Column(Integer, default=0)

    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    cluster = relationship("LookalikeCluster", back_populates="runs")
