"""add_crm_sync_fields_to_contacts

Revision ID: 2fb87aa98654
Revises: 202602010300
Create Date: 2026-02-03 01:46:38.551262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb87aa98654'
down_revision: Union[str, None] = '202602010300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('smartlead_id', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('getsales_id', sa.String(length=100), nullable=True))
    op.add_column('contacts', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('smartlead_status', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('getsales_status', sa.String(length=50), nullable=True))
    op.add_column('contacts', sa.Column('has_replied', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('last_reply_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('reply_channel', sa.String(length=50), nullable=True))
    op.create_index('ix_contacts_getsales', 'contacts', ['getsales_id'], unique=False)
    op.create_index(op.f('ix_contacts_getsales_id'), 'contacts', ['getsales_id'], unique=False)
    op.create_index(op.f('ix_contacts_has_replied'), 'contacts', ['has_replied'], unique=False)
    op.create_index('ix_contacts_linkedin', 'contacts', ['linkedin_url'], unique=False)
    op.create_index('ix_contacts_smartlead', 'contacts', ['smartlead_id'], unique=False)
    op.create_index(op.f('ix_contacts_smartlead_id'), 'contacts', ['smartlead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_smartlead_id'), table_name='contacts')
    op.drop_index('ix_contacts_smartlead', table_name='contacts')
    op.drop_index('ix_contacts_linkedin', table_name='contacts')
    op.drop_index(op.f('ix_contacts_has_replied'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_getsales_id'), table_name='contacts')
    op.drop_index('ix_contacts_getsales', table_name='contacts')
    op.drop_column('contacts', 'reply_channel')
    op.drop_column('contacts', 'last_reply_at')
    op.drop_column('contacts', 'has_replied')
    op.drop_column('contacts', 'getsales_status')
    op.drop_column('contacts', 'smartlead_status')
    op.drop_column('contacts', 'last_synced_at')
    op.drop_column('contacts', 'getsales_id')
    op.drop_column('contacts', 'smartlead_id')
    # ### end Alembic commands ###
