"""add_call_transcripts_table

Revision ID: ca40aae5085e
Revises: 202603161900
Create Date: 2026-03-16 22:39:13.655603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca40aae5085e'
down_revision: Union[str, None] = '202603162000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('fireflies_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('speakers', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('sentences', sa.JSON(), nullable=True),
    sa.Column('transcript_url', sa.String(length=1000), nullable=True),
    sa.Column('audio_url', sa.String(length=1000), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_transcripts_contact_date', 'call_transcripts', ['contact_id', 'date'], unique=False)
    op.create_index(op.f('ix_call_transcripts_contact_id'), 'call_transcripts', ['contact_id'], unique=False)
    op.create_index('ix_call_transcripts_date', 'call_transcripts', ['date'], unique=False)
    op.create_index(op.f('ix_call_transcripts_fireflies_id'), 'call_transcripts', ['fireflies_id'], unique=True)
    op.create_index(op.f('ix_call_transcripts_id'), 'call_transcripts', ['id'], unique=False)
    op.create_index(op.f('ix_call_transcripts_organizer_email'), 'call_transcripts', ['organizer_email'], unique=False)
    op.create_index(op.f('ix_call_transcripts_project_id'), 'call_transcripts', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_transcripts_project_id'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_organizer_email'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_id'), table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_fireflies_id'), table_name='call_transcripts')
    op.drop_index('ix_call_transcripts_date', table_name='call_transcripts')
    op.drop_index(op.f('ix_call_transcripts_contact_id'), table_name='call_transcripts')
    op.drop_index('ix_call_transcripts_contact_date', table_name='call_transcripts')
    op.drop_table('call_transcripts')
    # ### end Alembic commands ###
